### ISSUE TITLE
version 0.2.2

### ISSUE THREAD

**Issue by gitanat** [bkonkle/update-ip#1]
Hi Brandon,
I did a couple more commits and I think it warrants a new minor release, can you take a quick look?

Thanks!

**Comment by bkonkle** [comment]
Hi! It's been quite awhile, hasn't it? :smile: I'm glad you're still getting value out of update-ip!

It looks like you're already set up as a maintainer on PyPi:

![screen shot 2016-01-12 at 5 10 58 pm](https://cloud.githubusercontent.com/assets/30199/12280989/8f7e73c0-b94f-11e5-82b7-11afa898f864.png)

You should be able to publish. Let me know if you run into any trouble.

Thanks for contributing so much!

**Comment by gitanat** [comment]
Hey,
True, I've been running it on cron continuously for 4 years on multiple connections, it's quite robust! The latest connection I'm running it on seems flaky, so just I added a simple retry mechanism. 

You're right about pypi, of course, I had forgotten about that! Uploaded 0.2.2. Thanks for letting me contribute to the project!

Have a great 2016!
